### ISSUE TITLE
RandomColors メソッドの例外がスローされる

### ISSUE THREAD

**Issue by takunology** [takunology/MinecraftConnection#24]
例えば下記のように `RandomColors()` メソッドで複数の色を取得してインスタンスを作るまでは問題ない。

```cs
Fireworks fw = new Fireworks()
{
    LifeTime = 30,
    Type = FireworkType.LargeBall,
    Colors = FireworkOption.RandomColors(2),
};
```

しかし、花火を打ち上げようと `SetOffFireworks()` を使用すると例外がスローされる

```txt
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at MinecraftConnection.RCON.Encoder.DecodePacket(Byte[] bytes)
   at MinecraftConnection.RCON.MinecraftRCON.SendPacket(Packet request, Packet& response)
   at MinecraftConnection.RCON.MinecraftRCON.SendCommand(String command)
   at MinecraftConnection.MinecraftCommands.SetOffFireworks(Double x, Double y, Double z, Fireworks fireworks)
   at Program.<Main>$(String[] args) in C:\Users\takun\Desktop\App\Program.cs:line 16
```

**Comment by takunology** [comment]
NBT 確認したらエグかったｗ
これどこかでループしちゃってる可能性あるかな

```txt
{"LifeTime":30,"FireworksItem":{"id":"firework_rocket","Count":1,"tag":{"Fireworks":{"Flight":2,"Explosions":[{"Type":1,"Flicker":0,"Trail":0,"Colors":[I;4312372,11743532,5320730,6719955,15435844,8073150,6719955,4312372,11250603,12801229,12801229,4312372,3887386,6719955,11743532,11743532,2651799,14188952,14602026,12801229,5320730,8073150,15435844,6719955,2651799,5320730,14602026,2651799,1973019,4408131,11250603,1973019,1973019,12801229,3887386,6719955,12801229,12801229,11250603,14188952,6719955,8073150,6719955,14188952,1973019,2437522,5320730,3887386,5320730,14188952,14602026,4408131,11743532,4312372,1973019,12801229,12801229,1973019,4312372,3887386,5320730,4408131,6719955,14188952,2651799,14602026,15435844,1973019,14602026,15435844,8073150,2651799,11743532,12801229,1973019,1973019,5320730,12801229,2651799,4408131,11743532,12801229,3887386,5320730,1973019,3887386,6719955,8073150,8073150,11250603,5320730,15435844,2437522,14602026,3887386,6719955,5320730,5320730,1973019,15790320,14188952,15435844,8073150,11250603,3887386,14188952,3887386,15435844,14188952,4312372,11250603,5320730,4312372,4312372,3887386,6719955,1973019,5320730,15790320,4408131,2437522,6719955,4312372,2651799,2437522,14188952,11250603,8073150,2651799,11743532,4408131,2437522,11250603,11250603,5320730,15435844,6719955,2437522,5320730,15435844,14602026,4408131,6719955,14188952,14602026,4312372,15790320,15790320,11250603,12801229,6719955,11743532,15790320,4408131,3887386,15790320,4312372,2651799,4312372,3887386,6719955,5320730,2651799,2437522,15435844,14188952,14188952,15435844,5320730,2437522,3887386,6719955,11250603,4312372,14602026,12801229,15790320,11743532,11250603,2651799,11743532,14602026,5320730,15790320,12801229,11743532,15435844,12801229,15790320,12801229,3887386,6719955,2437522,3887386,11250603,11250603,2651799,6719955,12801229,14602026,15790320,8073150,5320730,2651799,8073150,4312372,3887386,3887386,15435844,8073150,11743532,5320730,12801229,14602026,15790320,8073150,11250603,3887386,15790320,1973019,8073150,5320730,2651799,11250603,4312372,14188952,4408131,14602026,14188952,4408131,8073150,8073150,1973019,14602026,2651799,4312372,2651799,4408131,11250603,8073150,4408131,2437522,14602026,4408131,4408131,15790320,11743532,11250603,3887386,3887386,15790320,3887386,4408131,11250603],"FadeColors":[I;]}]}}}} 
```

**Comment by takunology** [comment]
インクリメントが悪さしてた。なんで引数をインクリメントしとんねん。

<img width="474" alt="image" src="https://user-images.githubusercontent.com/29680473/230777358-9ae32664-d465-48f6-b5a8-7bc9f29aaa7a.png">

**Comment by takunology** [comment]
テストOK

```txt
{"LifeTime":30,"FireworksItem":{"id":"firework_rocket","Count":1,"tag":{"Fireworks":{"Flight":2,"Explosions":[{"Type":0,"Flicker":0,"Trail":0,"Colors":[I;12801229,14602026,12801229,4312372,8073150],"FadeColors":[I;2437522,1973019]}]}}}}
```
